function soccersystem(){var cb='',_=' top: -1000px;',zb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',ib='");',Ab='#',jc='.cache.js',Cb='/',Ib='//',cc='32DC01C306EFD205E94A964E21222FE5',dc='367E4ECCC63C1D79D5650145389A12EA',ec='43CE9F8CBDE87157B56A57E72D06A2E1',fc='618118BC9FD89E49392FBC81C6BBC75F',gc='73233B2B293C707FB06BA00207D85AA9',hc='8EF76A944F01D1F82DF32D9307F8C1D0',ic=':',rb='::',wc=':moduleBase',bb='<!doctype html>',db='<html><head><\/head><body><\/body><\/html>',ub='=',Bb='?',wb='Bad handler "',ab='CSS1Compat',gb='Chrome',fb='DOMContentLoaded',W='DUMMY',vc='Ignoring non-whitelisted Dev Mode URL: ',uc='__gwtDevModeHook:soccersystem',tc='_gwt_dummy_',Kb='android',Hb='base',Fb='baseUrl',R='begin',Ob='blackberry',X='body',Q='bootstrap',Eb='clear.cache.gif',tb='content',qc='end',hb='eval("',sc='file:',Pb='file://',Zb='gecko',$b='gecko1_8',S='gwt.codesvr.soccersystem=',T='gwt.codesvr=',pc='gwt/clean/clean.css',yb='gwt:onLoadErrorFn',vb='gwt:onPropertyErrorFn',sb='gwt:property',nb='head',nc='href',rc='http:',Wb='ie10',Yb='ie8',Xb='ie9',Y='iframe',Db='img',Lb='ipad',Nb='iphone',Mb='ipod',kb='javascript',Z='javascript:""',kc='link',oc='loadExternalRefs',ob='meta',mb='moduleRequested',lb='moduleStartup',Vb='msie',pb='name',Rb='no',Jb='phonegap.env',$='position:absolute; width:0; height:0; border:none; left: -1000px;',lc='rel',Ub='safari',jb='script',ac='selectingPermutation',U='soccersystem',bc='soccersystem.devmode.js',Gb='soccersystem.nocache.js',qb='soccersystem::',V='startup',mc='stylesheet',eb='undefined',_b='unknown',Sb='user.agent',Tb='webkit',Qb='yes';var o=window;var p=document;r(Q,R);function q(){var a=o.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:U,sessionId:o.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
soccersystem.__sendStats=r;soccersystem.__moduleName=U;soccersystem.__errFn=null;soccersystem.__moduleBase=W;soccersystem.__softPermutationId=0;soccersystem.__computePropValue=null;soccersystem.__getPropMap=null;soccersystem.__gwtInstallCode=function(){};soccersystem.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[U]={moduleName:U};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(X)[0]}
function B(){if(v){return}var a=p.createElement(Y);a.src=Z;a.id=U;a.style.cssText=$+_;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==ab?bb:cb;v.write(b+db);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==eb){return typeof p.body!=eb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ib));g=f.createElement(jb);g.language=kb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(jb);g.language=kb;g.text=c[i];e.appendChild(g);d(e,g)}}}
soccersystem.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;p.getElementsByTagName(nb)[0].appendChild(n)}
soccersystem.__startLoadingFragment=function(a){return G(a)};soccersystem.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(jb);c.language=kb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,cb);if(j.indexOf(rb)>=0){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=cb}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;soccersystem.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=0?a.substring(0,d+1):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=t(Fb);if(a!=null){return a}return cb}
function h(){var a=p.getElementsByTagName(jb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=p.getElementsByTagName(Hb);if(a.length>0){return a[a.length-1].href}return cb}
function j(){var a=p.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return soccersystem.__moduleBase+a}
function H(){var f=[];var g=0;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Jb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Kb)!=-1||(a.indexOf(Lb)!=-1||(a.indexOf(Mb)!=-1||(a.indexOf(Nb)!=-1||a.indexOf(Ob)!=-1)))){var b=document.location.href;if(b.indexOf(Pb)===0){return Qb}}return Rb}};i[Jb]={no:0,yes:1};j[Sb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=10}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=9}())return Xb;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=8}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};i[Sb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};s=function(a,b){return b in i[a]};soccersystem.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};soccersystem.__computePropValue=k;o.__gwt_activeModules[U].bindings=soccersystem.__getPropMap;r(Q,ac);if(q()){return G(bc)}var l;try{h([Rb,Yb],cc);h([Rb,Wb],dc);h([Qb,Ub],ec);h([Rb,Xb],fc);h([Rb,$b],gc);h([Rb,Ub],hc);l=f[k(Jb)][k(Sb)];var m=l.indexOf(ic);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}soccersystem.__softPermutationId=g;return G(l+jc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(kc);b.setAttribute(lc,mc);b.setAttribute(nc,G(a));p.getElementsByTagName(nb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(oc,R);c(pc);r(oc,qc)}
D();soccersystem.__moduleBase=F();u[U].moduleBase=soccersystem.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==rc||o.location.protocol==sc);o.__gwt_activeModules[U].canRedirect=K;function L(){var b=tc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=uc;var N=o.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(vc+N)}N=cb}if(N&&!o[M]){o[M]=true;o[M+wc]=F();var O=p.createElement(jb);O.src=N;var P=p.getElementsByTagName(nb)[0];P.insertBefore(O,P.firstElementChild||P.children[0]);return false}}}I();r(Q,qc);C(J);return true}
soccersystem.succeeded=soccersystem();